language: node_js
node_js:
- '8'
before_install: npm install npm@$(cat package.json | jq -r '.engines.npm') -g
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: breath103@gmail.com
  skip_cleanup: true
  api_key:
    secure: dJtKoKuRBTduXYHYh3ui43STMl8V5qAOdTFAZmvO+uP+3QZ1bpcwJD+9hKXMQt7jazdkslrRZbXbw2WSO98Mox+qDa2IJFReeKAIKxL5JcXVRAghl3pti9d6PwodXg6l//Ra1JUK729v+QyOOHjeok4mth6SLcnWWcEV3UOt7vWiekF7bHTecdZ5j9Shj9MlfxGJRHIC+5lYnYf4xlaAC2m20wNoihGD5RWCKZJa4bOXkIgbhU+Ex+bUCW8M5e33c/Q1gYQYM2zxoyHZwvrnkFTS50jVDvk51svD9Qr0tRv4UVUVPnWhmPXCNL0jJSmYRyYx2kHDq6tAchIOLRtrj2tHJdl6Mn8zgvElad5Xra2H6GkrcCu9KFUdkYetboVS2ZJHwoXf+2zuvZuCZtgY57Ej21mxqL1IVK2CjJuFWjU8yt/lptvJ0ibnhI0ad8t7j6mSle/Eii24UNL5Rg4EhJ+q/uHQQa9fQTU+xALlyBMs7AOmCQIKCgi07lhkSceaERktC1sAH8lOWs9wf+UmCFTOkUqQbfmscTyz8qlBEv42vMsvw0dXvYDP0QHJd8qd+kOIVblgEdAinING/N74vyhuHyhUmeYmRuAVMj6g3JvzYao5lJk2ryXiCgiB5wQNGVpb/uYC0L5zkzjwGees2D0YuP8OH91ZHxuA9kXb7JM=
  on:
    branch: master
